# 测试配置文件
# cmp
# 
server:
  port: 8101
  servlet:
    context-path: /dev-api
spring:
  # 数据库配置
  # todo 需替换配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cmp
    username: root
    password: root
  # redis 配置
  redis:
    database: 1
    host: 0.0.0.0
    port: 6379
    timeout: 5000

